---
name: metrics-gate
"on":
  pull_request:

jobs:
  gate:
    uses: >-
      webuildstuffio/repo-review/.github/workflows/metrics-reusable.yml@206487d9a11a53864f659eb24b65cddf7eaa344e
    with:
      run_snapshot: false
      language: shell
    secrets: inherit
