---
name: metrics-gate
"on":
  pull_request:

jobs:
  gate:
    uses: >-
      webuildstuffio/repo-review/.github/workflows/metrics-reusable.yml@e9a2d213d0b1691d4ba0d12b99f5d34f80b1bda2
    with:
      run_snapshot: false
      language: shell
    secrets: inherit
