---
name: metrics-weekly
"on":
  schedule:
    - cron: "0 13 * * *"  # daily 09:00 ET
  release:
    types: [published]
  workflow_dispatch:

jobs:
  snapshot:
    uses: >-
      webuildstuffio/repo-review/.github/workflows/metrics-reusable.yml@206487d9a11a53864f659eb24b65cddf7eaa344e
    with:
      run_snapshot: true
      language: typescript
      activity_window: '24 hours ago'
    secrets: inherit
